### ISSUE TITLE
Create a trashcan for the application

### ISSUE THREAD

**Issue by Shahar-Y** [meateam/drive-project#116]
Create a trash-can for deleted files.
This includes: 
- [ ] A full architecture-manifest on how to implement the feature (3 days): 
1. which services are effected, and where the changes should occur in them.
2. The changes in api necessary 
3. The new types sent in the inner api of the grpc. 
* Try to avoid breaking changes in the REST API.
- [ ] Open and document the issues in the services.
- [ ] Implementation: bottom-up changes in the services (The assignee will specify). - (8 days)
- [ ] Add related tests in all of the services. (2 days)
