### ISSUE TITLE
Service Provider

### ISSUE THREAD

**Issue by yonatandt** [meateam/drive-project#50]
#### Auth & Spike
- [x] define the new scopes
- [x] edit the oauth-middleware to fit the new auth-flow
- [x] apply auth-scopes middlewares where needed
- [x] validate the spike token
- [x] extract the scopes, user and client from the token
##### not urgent
- [x] get all approved clients of a user

#### File
- [x] A different client cannot access files which are not associated with it.
- [x] create files which associate with a different client with a new `app` field
- [x] filter out files created by another client when displaying "my files" and "files shared with me"
- [x] On demand, for a specific client and user, return all the root files (of the client), and the files directly shared with the user. 

#### Web-UI
- [x] Disable actions on files with appIDs which do not belong to the drive.
- [x] GetFilesByFolder, when parent is undefined, return only drive files.

#### API-GW
- [x] Create a method for "isBelongToApp(fileID, appID) : bool" - what about drive can do any action?
- [x] For every action,  check that appID is valid in the jwt vs the file.appID

**Comment by Shahar-Y** [comment]
All done and tested. Closing.
