### ISSUE TITLE
Re-purpose permit service

### ISSUE THREAD

**Issue by yonatandt** [meateam/drive-project#75]
- [x]  From now on, the permits will be received from the Approval-service, and will not be saved to the mongo.

- [x] Add spike authentication.

- [x] The status will be received from status-service, by file-ID and user-ID.

- [x] Delete the PUT request for updating the status.

**Comment by Shahar-Y** [comment]
I believe we can safely close this issue
